# Generated by Django 4.2.7 on 2026-02-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.TextField(max_length=10000)),
                ('css_code', models.TextField(max_length=10000)),
                ('code_length', models.IntegerField(help_text='Total character count of HTML + CSS')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
