# Generated by Django 4.2.7 on 2026-02-20 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'challenge'], name='submissions_user_id_5a282c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge'], name='submissions_challen_1bafa7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_9b96b8_idx'),
        ),
    ]
