# Generated by Django 4.2.7 on 2026-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rendered_image',
            field=models.ImageField(blank=True, help_text='Rendered PNG screenshot of submission', null=True, upload_to='submission_renders/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Similarity score from heatmap comparison (0.0-1.0)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status of the submission', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['similarity_score'], name='submissions_similar_6d6fc8_idx'),
        ),
    ]
