# Generated by Django 4.2.7 on 2026-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('html_boilerplate', models.TextField(help_text='Starting HTML code for participants')),
                ('css_boilerplate', models.TextField(help_text='Starting CSS code for participants')),
                ('points', models.IntegerField(default=100, help_text='Points awarded for solving this challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['created_at'],
            },
        ),
    ]
