# Generated by Django 4.2.7 on 2026-02-28 14:45

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['created_at'], 'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenge'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='palette',
            field=models.CharField(blank=True, help_text='Comma-separated hex colors (e.g., #FF5733,#33FF57,#3357FF)', max_length=500, validators=[challenges.models.validate_palette]),
        ),
        migrations.AddField(
            model_name='challenge',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for the challenge', null=True, upload_to='challenge_previews/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='css_boilerplate',
            field=models.TextField(help_text='Type your CSS code here.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='html_boilerplate',
            field=models.TextField(help_text='type your HTML code here.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=100, help_text='Points Awarded!!'),
        ),
    ]
