# Generated by Django 4.2.7 on 2026-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_options_challenge_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ground_truth_image',
            field=models.ImageField(blank=True, help_text='Reference image for heatmap comparison', null=True, upload_to='challenge_ground_truths/'),
        ),
    ]
