# Generated by Django 4.2.7 on 2026-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_session_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_ip_addr_340a7c_idx',
            old_name='login_attem_ip_addr_8a9b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_registe_e76135_idx',
            old_name='login_attem_registe_7d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_success_f3dfbd_idx',
            old_name='login_attem_success_6c3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='security_al_alert_t_7bbcd8_idx',
            old_name='security_al_alert_t_b0c2c4_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='security_al_severit_d48cb6_idx',
            old_name='security_al_severit_4c4b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='securityalert',
            new_name='security_al_created_2111fe_idx',
            old_name='security_al_created_c8b7a5_idx',
        ),
        migrations.AlterField(
            model_name='ipmonitoring',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
